version: "2"

reviews:
  poem: false
  request_changes_workflow: false
  high_level_summary: true
  review_status: true
  auto_review:
    enabled: true
    drafts: false

  tools:
    github-checks:
      enabled: true
      timeout_ms: 90000

chat:
  auto_reply: true
